### ISSUE TITLE
බලපන් Readme එකේ කැත

### ISSUE THREAD

**Issue by RavOfficial** [iamtrazy/rezoth-ssh#6]
Dear IAmTrazy,
ඕයි බලහන් යකෝ Readme එකෙ තියෙන unicodes ගොඩ, ඒ අකුරු කියවන්න බෑ, වෙනස් කරහන් කරුනාකරලා.
අනිත් එක මේක Rezoth Project එකක් හින්දා Rezoth Team එකටම credits යන්න ඕනේ, එකෙක්ට විතරක් නිකන් contribution දැම්මා කියලා dev කෙනෙක් වෙන්නෑ.
තව readme එක විතරක් edit කරා කියලත් dev කෙනෙක් වෙන්නෑනේ සිරාවටම කිව්වොත්.
ඒක හින්දා එතනත් පොජ්ජක් බලලා එඩිට් කොරලා දාන්න හොදේ.

Thank You!
Bawwa Official.

**Comment by Ash-Boi** [comment]
> Dear IAmTrazy,
> ඕයි බලහන් යකෝ Readme එකෙ තියෙන unicodes ගොඩ, ඒ අකුරු කියවන්න බෑ, වෙනස් කරහන් කරුනාකරලා.
> අනිත් එක මේක Rezoth Project එකක් හින්දා Rezoth Team එකටම credits යන්න ඕනේ, එකෙක්ට විතරක් නිකන් contribution දැම්මා කියලා dev කෙනෙක් වෙන්නෑ.
> තව readme එක විතරක් edit කරා කියලත් dev කෙනෙක් වෙන්නෑනේ සිරාවටම කිව්වොත්.
> ඒක හින්දා එතනත් පොජ්ජක් බලලා එඩිට් කොරලා දාන්න හොදේ.
> 
> Thank You!
> Bawwa Official.

ammoo eeka

**Comment by AnjanaMadu** [comment]
> Dear IAmTrazy,
> ඕයි බලහන් යකෝ Readme එකෙ තියෙන unicodes ගොඩ, ඒ අකුරු කියවන්න බෑ, වෙනස් කරහන් කරුනාකරලා.
> අනිත් එක මේක Rezoth Project එකක් හින්දා Rezoth Team එකටම credits යන්න ඕනේ, එකෙක්ට විතරක් නිකන් contribution දැම්මා කියලා dev කෙනෙක් වෙන්නෑ.
> තව readme එක විතරක් edit කරා කියලත් dev කෙනෙක් වෙන්නෑනේ සිරාවටම කිව්වොත්.
> ඒක හින්දා එතනත් පොජ්ජක් බලලා එඩිට් කොරලා දාන්න හොදේ.
> 
> Thank You!
> Bawwa Official.

ekagayi ++

**Comment by YKavishka22** [comment]
> Dear IAmTrazy,
> ඕයි බලහන් යකෝ Readme එකෙ තියෙන unicodes ගොඩ, ඒ අකුරු කියවන්න බෑ, වෙනස් කරහන් කරුනාකරලා.
> අනිත් එක මේක Rezoth Project එකක් හින්දා Rezoth Team එකටම credits යන්න ඕනේ, එකෙක්ට විතරක් නිකන් contribution දැම්මා කියලා dev කෙනෙක් වෙන්නෑ.
> තව readme එක විතරක් edit කරා කියලත් dev කෙනෙක් වෙන්නෑනේ සිරාවටම කිව්වොත්.
> ඒක හින්දා එතනත් පොජ්ජක් බලලා එඩිට් කොරලා දාන්න හොදේ.
> 
> Thank You!
> Bawwa Official.

අන්නේකයි.
සිරාවටම බලාන් සමහර topics පෙන්නෑ.
(pic එකක් attached කරලා තියෙනවා)
![IMG_20210718_222600_000](https://user-images.githubusercontent.com/82832345/126075790-30ec0aba-610d-40be-ba07-08b96225d580.jpg)

**Comment by AnjanaMadu** [comment]
> > Dear IAmTrazy,
> > ඕයි බලහන් යකෝ Readme එකෙ තියෙන unicodes ගොඩ, ඒ අකුරු කියවන්න බෑ, වෙනස් කරහන් කරුනාකරලා.
> > අනිත් එක මේක Rezoth Project එකක් හින්දා Rezoth Team එකටම credits යන්න ඕනේ, එකෙක්ට විතරක් නිකන් contribution දැම්මා කියලා dev කෙනෙක් වෙන්නෑ.
> > තව readme එක විතරක් edit කරා කියලත් dev කෙනෙක් වෙන්නෑනේ සිරාවටම කිව්වොත්.
> > ඒක හින්දා එතනත් පොජ්ජක් බලලා එඩිට් කොරලා දාන්න හොදේ.
> > Thank You!
> > Bawwa Official.
> 
> අන්නේකයි.
> සිරාවටම බලාන් සමහර topics පෙන්නෑ.
> (pic එකක් attached කරලා තියෙනවා)
> ![IMG_20210718_222600_000](https://user-images.githubusercontent.com/82832345/126075790-30ec0aba-610d-40be-ba07-08b96225d580.jpg)

iya neda

**Comment by dasunpamod** [comment]
> Dear IAmTrazy,
> ඕයි බලහන් යකෝ Readme එකෙ තියෙන unicodes ගොඩ, ඒ අකුරු කියවන්න බෑ, වෙනස් කරහන් කරුනාකරලා.
> අනිත් එක මේක Rezoth Project එකක් හින්දා Rezoth Team එකටම credits යන්න ඕනේ, එකෙක්ට විතරක් නිකන් contribution දැම්මා කියලා dev කෙනෙක් වෙන්නෑ.
> තව readme එක විතරක් edit කරා කියලත් dev කෙනෙක් වෙන්නෑනේ සිරාවටම කිව්වොත්.
> ඒක හින්දා එතනත් පොජ්ජක් බලලා එඩිට් කොරලා දාන්න හොදේ.
> 
> Thank You!
> Bawwa Official.



> > Dear IAmTrazy,
> > ඕයි බලහන් යකෝ Readme එකෙ තියෙන unicodes ගොඩ, ඒ අකුරු කියවන්න බෑ, වෙනස් කරහන් කරුනාකරලා.
> > අනිත් එක මේක Rezoth Project එකක් හින්දා Rezoth Team එකටම credits යන්න ඕනේ, එකෙක්ට විතරක් නිකන් contribution දැම්මා කියලා dev කෙනෙක් වෙන්නෑ.
> > තව readme එක විතරක් edit කරා කියලත් dev කෙනෙක් වෙන්නෑනේ සිරාවටම කිව්වොත්.
> > ඒක හින්දා එතනත් පොජ්ජක් බලලා එඩිට් කොරලා දාන්න හොදේ.
> > Thank You!
> > Bawwa Official.
> 
> අන්නේකයි.
> සිරාවටම බලාන් සමහර topics පෙන්නෑ.
> (pic එකක් attached කරලා තියෙනවා)
> ![IMG_20210718_222600_000](https://user-images.githubusercontent.com/82832345/126075790-30ec0aba-610d-40be-ba07-08b96225d580.jpg)

ube phone eka support na bn :( font eka  oka ithin mukuth kiyalth ba nokiyth ba

**Comment by Savinda12** [comment]
> Dear IAmTrazy,
> ඕයි බලහන් යකෝ Readme එකෙ තියෙන unicodes ගොඩ, ඒ අකුරු කියවන්න බෑ, වෙනස් කරහන් කරුනාකරලා.
> අනිත් එක මේක Rezoth Project එකක් හින්දා Rezoth Team එකටම credits යන්න ඕනේ, එකෙක්ට විතරක් නිකන් contribution දැම්මා කියලා dev කෙනෙක් වෙන්නෑ.
> තව readme එක විතරක් edit කරා කියලත් dev කෙනෙක් වෙන්නෑනේ සිරාවටම කිව්වොත්.
> ඒක හින්දා එතනත් පොජ්ජක් බලලා එඩිට් කොරලා දාන්න හොදේ.
> 
> Thank You!
> Bawwa Official.

https://github.com/Savinda12/rezoth-ssh

මෙ මගෙ එක මගෙ එකෙත් යට කොනක මගෙ නම තියෙන්නෙ🌚

**Comment by sirimathxd** [comment]
> Dear IAmTrazy,
> ඕයි බලහන් යකෝ Readme එකෙ තියෙන unicodes ගොඩ, ඒ අකුරු කියවන්න බෑ, වෙනස් කරහන් කරුනාකරලා.
> අනිත් එක මේක Rezoth Project එකක් හින්දා Rezoth Team එකටම credits යන්න ඕනේ, එකෙක්ට විතරක් නිකන් contribution දැම්මා කියලා dev කෙනෙක් වෙන්නෑ.
> තව readme එක විතරක් edit කරා කියලත් dev කෙනෙක් වෙන්නෑනේ සිරාවටම කිව්වොත්.
> ඒක හින්දා එතනත් පොජ්ජක් බලලා එඩිට් කොරලා දාන්න හොදේ.
> 
> Thank You!
> Bawwa Official.

https://github.com/Savinda12/rezoth-ssh අර කලු ජාතික අත්දෙක දික් කරන් ඉන්න මිනිහ

**Comment by VidathD** [comment]
ammo ithin lol

**Comment by VidathD** [comment]
Changelogs readme eke danna epa.
